---
- name: 'Prepare'
  hosts: 'all'
  tasks:
  - name: 'Update package cache'
    when: ansible_os_family == 'Debian'
    ansible.builtin.package:
      update_cache: true
      cache_valid_time: 3600
